### PR TITLE
Fix kubernetes cluster operations

### LINKED ISSUE #29: Kubernetes Cluster operations does not work
Image

### PR DESCRIPTION
**Pull request by darashevcstbg**

### CODE REVIEW

**Review by bpavlov-daiteap — CHANGES_REQUESTED** [review]
ClusterDetails component does not use cluster operations. Please remove them from the component.

**Review by bpavlov-daiteap — CHANGES_REQUESTED** [review]
In OperationsTab and KubernetesClustersTable components cluster operations' dialogs are not used. Please remove them from the components.

**Comment by darashevcstbg** [comment]
> ClusterDetails component does not use cluster operations

Added missing dialogs in another PR https://github.com/Daiteap/daiteap-ui/pull/34/commits/832d0c67da2efe7f9f670dea29e9ce48f899c514

**Review by bpavlov-daiteap — CHANGES_REQUESTED** [review]
Cluster operations' dialogs are not used in KubernetesClustersTable component. Please remove them from the component or make them be used.

**Review by bpavlov-daiteap — APPROVED** [review]
LGTM

**Pull request merged**
