### PR TITLE
Update NPM packages

### PR DESCRIPTION
**Pull request by bpavlov-daiteap**

### CODE REVIEW

**Comment by akafazov** [comment]
@bpavlov-daiteap unit tests are failing

**Review by akafazov — CHANGES_REQUESTED** [review]
fix tests

**Comment by darashevcstbg** [comment]
I get an error starting the frontend:

`Uncaught Error: The 'Keycloak' constructor must be invoked with 'new'.`

**Review by akafazov — APPROVED** [review]
lgtm

**Review by darashevcstbg — COMMENTED** [review]
LGTM

**Pull request merged**
